#Stage 1: Builder (golang:1.23-alpine)
FROM golang:1.24-alpine AS builder

RUN apk add --no-cache git

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o agent ./cmd/agent

#Stage 2: Runtime (alpine:latest)
FROM alpine:latest

RUN apk add --no-cache ca-certificates

WORKDIR /app

# Create a non-root user for security
RUN adduser -D logflow
COPY --from=builder /app/agent .
RUN chown -R logflow:logflow /app

USER logflow

CMD ["./agent"]
